name: Build OpenWrt

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    
    steps:
      - name: Installation depends
        run: |
          sudo apt-get update
          sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget curl swig rsync
          
      - name: Clone source code
        run: git clone https://github.com/coolsnowwolf/lede
          
          
      - name: Load custom feeds
        run: |
          cd lede
          sed -i 's/^#\(.*helloworld\)/\1/' feeds.conf.default
          cd ./package/lean
          git clone https://github.com/jerrykuku/luci-app-jd-dailybonus.git
          git clone https://github.com/tty228/luci-app-serverchan.git
          git clone https://github.com/esirplayground/luci-app-poweroff.git
          git clone https://github.com/project-openwrt/openwrt-filebrowser.git
          

      
      - name: Update feeds
        run: cd lede && ./scripts/feeds update -a
        


      - name: Install feeds
        run: cd lede && ./scripts/feeds install -a
      
      
      - name: Modify default IP
        run: |
          cd lede
          sed -i 's/192.168.1.1/10.9.9.1/g' ./package/base-files/files/bin/config_generate
          sed -i 's/192.168/10.9/g' ./package/base-files/files/bin/config_generate
          sed -i "s/\(DISTRIB_REVISION='\(\w\|\.\)\+\)'/\1 Compiled by xiaofei'/" ./package/lean/default-settings/files/zzz-default-settings
      
      
      - name: Load custom configuration
        run: |
          mv .config lede/.config
          
      - name: Download package
        run: |
          cd lede
          make -j8 download
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;
          
          
      - name: Build
        run: |
          cd lede
          make -j$(nproc) || make -j1 || make -j1 V=s
          
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt
          path: lede/bin/targets/x86/64
          
          
          
